# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  API:
    image: grasindo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    networks:
      - grasindo
    
  database:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=grasindo_db
      - POSTGRES_PASSWORD=password
    networks:
      - grasindo



networks:
  grasindo: